/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cv.generator;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author 91975
 */
public class ResumeM extends javax.swing.JFrame {

    Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    /**
     * Creates new form ResumeM
     */
    public ResumeM() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, 
        size.height/2 - getHeight()/2);
        txtName.setBackground(new java.awt.Color(0,0,0,1));
        txtLastName.setBackground(new java.awt.Color(0,0,0,1));
        txtEmail.setBackground(new java.awt.Color(0,0,0,1));
        txtCode.setBackground(new java.awt.Color(0,0,0,1));
        txtPhone.setBackground(new java.awt.Color(0,0,0,1));
        txtCity.setBackground(new java.awt.Color(0,0,0,1));
        txtState.setBackground(new java.awt.Color(0,0,0,1));
        txtPro.setBackground(new java.awt.Color(0,0,0,1));
        txtClg.setBackground(new java.awt.Color(0,0,0,1));
        txtClgLoc.setBackground(new java.awt.Color(0,0,0,1));
        txtDegree.setBackground(new java.awt.Color(0,0,0,1));
        txtFOS.setBackground(new java.awt.Color(0,0,0,1));
        txtSYear.setBackground(new java.awt.Color(0,0,0,1));
        txtEYear.setBackground(new java.awt.Color(0,0,0,1));
        txtObjective.setBackground(new java.awt.Color(0,0,0,1));
        txtSkill1.setBackground(new java.awt.Color(0,0,0,1));
        txtSkill2.setBackground(new java.awt.Color(0,0,0,1));
        txtSkill3.setBackground(new java.awt.Color(0,0,0,1));
        txtSkill4.setBackground(new java.awt.Color(0,0,0,1));
        txtLang1.setBackground(new java.awt.Color(0,0,0,1));
        txtLang2.setBackground(new java.awt.Color(0,0,0,1));
        txtJob.setBackground(new java.awt.Color(0,0,0,1));
        txtEmployer.setBackground(new java.awt.Color(0,0,0,1));
        txtJobState.setBackground(new java.awt.Color(0,0,0,1));
        txtJobCity.setBackground(new java.awt.Color(0,0,0,1));
        txtJobSYear.setBackground(new java.awt.Color(0,0,0,1));
        txtJobEYear.setBackground(new java.awt.Color(0,0,0,1));
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPro = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtState = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtCode = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtClg = new javax.swing.JTextField();
        txtClgLoc = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtDegree = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtFOS = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtSYear = new javax.swing.JTextField();
        txtEYear = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSkill1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtSkill2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtSkill3 = new javax.swing.JTextField();
        txtSkill4 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtJob = new javax.swing.JTextField();
        txtEmployer = new javax.swing.JTextField();
        txtJobCity = new javax.swing.JTextField();
        txtJobState = new javax.swing.JTextField();
        txtJobSYear = new javax.swing.JTextField();
        txtJobEYear = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtJobDis = new javax.swing.JTextArea();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        txtLang1 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        txtLang2 = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnGenerate = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        txtObjective = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kGradientPanel1.setkEndColor(new java.awt.Color(255, 255, 1));
        kGradientPanel1.setkStartColor(java.awt.Color.red);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel4.setText("PERSONAL INFORMARION");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jLabel1.setText("First Name");

        txtName.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        txtName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNameKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jLabel2.setText("Last Name");

        txtLastName.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        txtLastName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastNameActionPerformed(evt);
            }
        });
        txtLastName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtLastNameKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jLabel5.setText("Profession");

        txtPro.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        txtPro.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProActionPerformed(evt);
            }
        });
        txtPro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtProKeyPressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jLabel6.setText("City");

        txtCity.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        txtCity.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCityActionPerformed(evt);
            }
        });
        txtCity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCityKeyPressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jLabel7.setText("State");

        txtState.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        txtState.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStateActionPerformed(evt);
            }
        });
        txtState.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtStateKeyPressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jLabel9.setText("Zip Code");

        txtCode.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        txtCode.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodeActionPerformed(evt);
            }
        });
        txtCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodeKeyPressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jLabel10.setText("Phone");

        txtPhone.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        txtPhone.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneActionPerformed(evt);
            }
        });
        txtPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPhoneKeyPressed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jLabel11.setText("Email");

        txtEmail.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        txtEmail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEmailKeyPressed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel19.setText("EDUCATION INFORMARION");

        jLabel20.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jLabel20.setText("College Name");

        jLabel21.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jLabel21.setText("College Location");

        txtClg.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        txtClg.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtClg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClgActionPerformed(evt);
            }
        });
        txtClg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtClgKeyPressed(evt);
            }
        });

        txtClgLoc.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        txtClgLoc.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtClgLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClgLocActionPerformed(evt);
            }
        });
        txtClgLoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtClgLocKeyPressed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jLabel22.setText("Degree");

        txtDegree.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        txtDegree.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtDegree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDegreeActionPerformed(evt);
            }
        });
        txtDegree.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDegreeKeyPressed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jLabel23.setText("Field of Study");

        txtFOS.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        txtFOS.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtFOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFOSActionPerformed(evt);
            }
        });
        txtFOS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFOSKeyPressed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jLabel24.setText("Graduation Start Year");

        jLabel25.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jLabel25.setText("Graduation End Year");

        txtSYear.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        txtSYear.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtSYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSYearActionPerformed(evt);
            }
        });
        txtSYear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSYearKeyPressed(evt);
            }
        });

        txtEYear.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        txtEYear.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtEYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEYearActionPerformed(evt);
            }
        });
        txtEYear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEYearKeyPressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel8.setText("SKILLS");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jLabel3.setText("Skills");

        txtSkill1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        txtSkill1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtSkill1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSkill1ActionPerformed(evt);
            }
        });
        txtSkill1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSkill1KeyPressed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jLabel12.setText("Skills");

        txtSkill2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        txtSkill2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtSkill2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSkill2ActionPerformed(evt);
            }
        });
        txtSkill2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSkill2KeyPressed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jLabel13.setText("Skills");

        txtSkill3.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        txtSkill3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtSkill3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSkill3ActionPerformed(evt);
            }
        });
        txtSkill3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSkill3KeyPressed(evt);
            }
        });

        txtSkill4.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        txtSkill4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtSkill4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSkill4ActionPerformed(evt);
            }
        });
        txtSkill4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSkill4KeyPressed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jLabel15.setText("Skills");

        txtJob.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        txtJob.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtJob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJobActionPerformed(evt);
            }
        });
        txtJob.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtJobKeyPressed(evt);
            }
        });

        txtEmployer.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        txtEmployer.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtEmployer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmployerActionPerformed(evt);
            }
        });
        txtEmployer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEmployerKeyPressed(evt);
            }
        });

        txtJobCity.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        txtJobCity.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtJobCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJobCityActionPerformed(evt);
            }
        });
        txtJobCity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtJobCityKeyPressed(evt);
            }
        });

        txtJobState.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        txtJobState.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtJobState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJobStateActionPerformed(evt);
            }
        });
        txtJobState.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtJobStateKeyPressed(evt);
            }
        });

        txtJobSYear.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        txtJobSYear.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtJobSYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJobSYearActionPerformed(evt);
            }
        });
        txtJobSYear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtJobSYearKeyPressed(evt);
            }
        });

        txtJobEYear.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        txtJobEYear.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtJobEYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJobEYearActionPerformed(evt);
            }
        });
        txtJobEYear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtJobEYearKeyPressed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jLabel16.setText("Start Year");

        jLabel17.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jLabel17.setText("End Year");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jLabel18.setText("State");

        jLabel26.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jLabel26.setText("City");

        jLabel27.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jLabel27.setText("Job Title");

        jLabel28.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jLabel28.setText("Employer");

        jLabel30.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jLabel30.setText("Discription");

        txtJobDis.setBackground(new java.awt.Color(255, 248, 1));
        txtJobDis.setColumns(20);
        txtJobDis.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        txtJobDis.setRows(5);
        txtJobDis.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtJobDis.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtJobDisKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(txtJobDis);

        jLabel31.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel31.setText("WORK HISTORY");

        jLabel32.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jLabel32.setText("Language");

        txtLang1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        txtLang1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtLang1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLang1ActionPerformed(evt);
            }
        });
        txtLang1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtLang1KeyPressed(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jLabel33.setText("Language");

        txtLang2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        txtLang2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtLang2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLang2ActionPerformed(evt);
            }
        });
        txtLang2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtLang2KeyPressed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(255, 255, 1));
        btnSave.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cv/generator/pngwing.com (22).png"))); // NOI18N
        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnGenerate.setBackground(new java.awt.Color(255, 255, 1));
        btnGenerate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnGenerate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cv/generator/pngegg (4).png"))); // NOI18N
        btnGenerate.setText("GENERATE");
        btnGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateActionPerformed(evt);
            }
        });

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cv/generator/pngwing.com (15).png"))); // NOI18N

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cv/generator/pngwing.com (17).png"))); // NOI18N

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cv/generator/pngwing.com (18).png"))); // NOI18N

        jLabel40.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel40.setText("LANGUAGES");

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cv/generator/pngwing.com (19).png"))); // NOI18N

        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cv/generator/pngwing.com (20).png"))); // NOI18N

        btnExit.setBackground(new java.awt.Color(255, 255, 1));
        btnExit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cv/generator/pngwing.com (9).png"))); // NOI18N
        btnExit.setText("EXIT");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cv/generator/pngwing.com (23).png"))); // NOI18N

        jLabel43.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel43.setText("OBJECTIVE");

        txtObjective.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtObjective.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtObjective.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtObjectiveActionPerformed(evt);
            }
        });
        txtObjective.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtObjectiveKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(txtObjective)
                        .addGap(198, 198, 198))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(638, 638, 638))
                            .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtPro, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, kGradientPanel1Layout.createSequentialGroup()
                                            .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel1)
                                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel2)
                                                .addComponent(txtLastName)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, kGradientPanel1Layout.createSequentialGroup()
                                            .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel6)
                                                .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel7)
                                                .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel9)
                                                    .addGap(0, 0, Short.MAX_VALUE))
                                                .addComponent(txtCode))))
                                    .addGap(46, 46, 46))
                                .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel11)
                                        .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                            .addComponent(txtEmail)
                                            .addGap(46, 46, 46))))
                                .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10)
                                        .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                            .addGap(4, 4, 4)
                                            .addComponent(jLabel37)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel4)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                            .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel20)
                                                .addComponent(txtClg, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel21)
                                                .addComponent(txtClgLoc)))
                                        .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                            .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel23)
                                                .addComponent(jLabel24)
                                                .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                                    .addComponent(txtSYear, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel25)
                                                        .addComponent(txtEYear, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addComponent(txtFOS, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                                            .addGap(0, 0, Short.MAX_VALUE)
                                            .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtLang1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtLang2, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel33)
                                                .addComponent(jLabel32)
                                                .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel42)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jLabel40)))))
                                    .addComponent(jLabel22)
                                    .addComponent(txtDegree, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(198, 198, 198))
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel38)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel19)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSkill1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSkill3, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSkill2, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15)
                            .addComponent(jLabel3)
                            .addComponent(txtSkill4, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel39)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8)))
                        .addGap(120, 120, 120)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel27)
                                            .addComponent(txtJob, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtEmployer, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel28)))
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel26)
                                            .addComponent(txtJobCity, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel18)
                                            .addComponent(txtJobState, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel30)
                                    .addComponent(jScrollPane2))
                                .addGap(90, 90, 90)
                                .addComponent(btnSave)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnGenerate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnExit)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel41)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel31))
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtJobSYear, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel16))
                                        .addGap(7, 7, 7)
                                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel17)
                                            .addComponent(txtJobEYear, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel43)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel43, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtObjective, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel37)
                    .addComponent(jLabel4)
                    .addComponent(jLabel19)
                    .addComponent(jLabel38))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtClg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtClgLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDegree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel39))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addGap(1, 1, 1)
                                .addComponent(txtSkill1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)
                                .addGap(3, 3, 3)
                                .addComponent(txtSkill2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(jLabel12)
                                .addGap(6, 6, 6)
                                .addComponent(txtSkill3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15)
                                .addGap(1, 1, 1)
                                .addComponent(txtSkill4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(132, 132, 132))
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel41)
                                    .addComponent(jLabel31))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel28))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtJob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEmployer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(2, 2, 2)
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel26)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtJobCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtJobState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addGap(26, 26, 26)))
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtJobSYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtJobEYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel30)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel40)
                            .addComponent(jLabel42))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel32)
                        .addGap(1, 1, 1)
                        .addComponent(txtLang1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel33)
                        .addGap(3, 3, 3)
                        .addComponent(txtLang2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSave)
                            .addComponent(btnGenerate)
                            .addComponent(btnExit))
                        .addGap(57, 57, 57))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1386, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_DOWN){
            txtPro.requestFocus();
        }
        if(evt.getKeyCode()==KeyEvent.VK_RIGHT){
            txtLastName.requestFocus();
        }
        if(evt.getKeyCode()==KeyEvent.VK_UP){
            txtObjective.requestFocus();
        }
    }//GEN-LAST:event_txtNameKeyPressed

    private void txtLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastNameActionPerformed

    private void txtLastNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLastNameKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_DOWN){
            txtPro.requestFocus();
        }
        if(evt.getKeyCode()==KeyEvent.VK_LEFT){
            txtName.requestFocus();
        }
        if(evt.getKeyCode()==KeyEvent.VK_RIGHT){
            txtClg.requestFocus();
        }
        if(evt.getKeyCode()==KeyEvent.VK_UP){
            txtObjective.requestFocus();
        }
    }//GEN-LAST:event_txtLastNameKeyPressed

    private void txtProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProActionPerformed

    private void txtProKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_DOWN){
            txtCity.requestFocus();
        }
        if(evt.getKeyCode()==KeyEvent.VK_UP){
            txtLastName.requestFocus();
        }
        if(evt.getKeyCode()==KeyEvent.VK_RIGHT){
            txtDegree.requestFocus();
        }
    }//GEN-LAST:event_txtProKeyPressed

    private void txtCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCityActionPerformed

    private void txtCityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCityKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_DOWN){
            txtPhone.requestFocus();
        }
        if(evt.getKeyCode()==KeyEvent.VK_RIGHT){
            txtState.requestFocus();
        }
        if(evt.getKeyCode()==KeyEvent.VK_UP){
            txtPro.requestFocus();
        }
    }//GEN-LAST:event_txtCityKeyPressed

    private void txtStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStateActionPerformed

    private void txtStateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStateKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_DOWN){
            txtPhone.requestFocus();
        }
        if(evt.getKeyCode()==KeyEvent.VK_RIGHT){
            txtCode.requestFocus();
        }
        if(evt.getKeyCode()==KeyEvent.VK_UP){
            txtPro.requestFocus();
        }
        if(evt.getKeyCode()==KeyEvent.VK_LEFT){
            txtCity.requestFocus();
        }
    }//GEN-LAST:event_txtStateKeyPressed

    private void txtCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodeActionPerformed

    private void txtCodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodeKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_DOWN){
            txtPhone.requestFocus();
        }

        if(evt.getKeyCode()==KeyEvent.VK_UP){
            txtPro.requestFocus();
        }
        if(evt.getKeyCode()==KeyEvent.VK_LEFT){
            txtState.requestFocus();
        }
        if(evt.getKeyCode()==KeyEvent.VK_RIGHT){
            txtFOS.requestFocus();
        }
    }//GEN-LAST:event_txtCodeKeyPressed

    private void txtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneActionPerformed

    private void txtPhoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhoneKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_UP){
            txtCode.requestFocus();
        }
        if(evt.getKeyCode()==KeyEvent.VK_RIGHT){
            txtEmail.requestFocus();
        }
        if(evt.getKeyCode()==KeyEvent.VK_DOWN){
            txtSkill1.requestFocus();
        }
    }//GEN-LAST:event_txtPhoneKeyPressed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_UP){
            txtCode.requestFocus();
        }
        if(evt.getKeyCode()==KeyEvent.VK_LEFT){
            txtPhone.requestFocus();
        }
        if(evt.getKeyCode()==KeyEvent.VK_RIGHT){
            txtSYear.requestFocus();
        }
        if(evt.getKeyCode()==KeyEvent.VK_DOWN){
            txtJob.requestFocus();
        }
    }//GEN-LAST:event_txtEmailKeyPressed

    private void txtClgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClgActionPerformed

    private void txtClgKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClgKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_DOWN){
            txtDegree.requestFocus();
        }
        if(evt.getKeyCode()==KeyEvent.VK_RIGHT){
            txtClgLoc.requestFocus();
        }
        if(evt.getKeyCode()==KeyEvent.VK_LEFT){
            txtLastName.requestFocus();
        }
        if(evt.getKeyCode()==KeyEvent.VK_UP){
            txtObjective.requestFocus();
        }
    }//GEN-LAST:event_txtClgKeyPressed

    private void txtClgLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClgLocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClgLocActionPerformed

    private void txtClgLocKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClgLocKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_DOWN){
            txtDegree.requestFocus();
        }
        if(evt.getKeyCode()==KeyEvent.VK_LEFT){
            txtClg.requestFocus();
        }
        if(evt.getKeyCode()==KeyEvent.VK_UP){
            txtObjective.requestFocus();
        }
    }//GEN-LAST:event_txtClgLocKeyPressed

    private void txtDegreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDegreeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDegreeActionPerformed

    private void txtDegreeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDegreeKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_DOWN){
            txtFOS.requestFocus();
        }
        if(evt.getKeyCode()==KeyEvent.VK_UP){
            txtClgLoc.requestFocus();
        }
        if(evt.getKeyCode()==KeyEvent.VK_LEFT){
            txtPro.requestFocus();
        }
    }//GEN-LAST:event_txtDegreeKeyPressed

    private void txtFOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFOSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFOSActionPerformed

    private void txtFOSKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFOSKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_DOWN){
            txtSYear.requestFocus();
        }
        if(evt.getKeyCode()==KeyEvent.VK_UP){
            txtDegree.requestFocus();
        }
        if(evt.getKeyCode()==KeyEvent.VK_LEFT){
            txtCode.requestFocus();
        }
    }//GEN-LAST:event_txtFOSKeyPressed

    private void txtSYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSYearActionPerformed

    private void txtSYearKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSYearKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_UP){
            txtFOS.requestFocus();
        }
        if(evt.getKeyCode()==KeyEvent.VK_RIGHT){
            txtEYear.requestFocus();
        }
        if(evt.getKeyCode()==KeyEvent.VK_LEFT){
            txtEmail.requestFocus();
        }
        if(evt.getKeyCode()==KeyEvent.VK_DOWN){
            txtEmployer.requestFocus();
        }
    }//GEN-LAST:event_txtSYearKeyPressed

    private void txtEYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEYearActionPerformed

    private void txtEYearKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEYearKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_UP){
            txtFOS.requestFocus();
        }
        if(evt.getKeyCode()==KeyEvent.VK_LEFT){
            txtSYear.requestFocus();
        }
        if(evt.getKeyCode()==KeyEvent.VK_DOWN){
            txtLang1.requestFocus();
        }
    }//GEN-LAST:event_txtEYearKeyPressed

    private void txtSkill1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSkill1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSkill1ActionPerformed

    private void txtSkill2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSkill2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSkill2ActionPerformed

    private void txtSkill3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSkill3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSkill3ActionPerformed

    private void txtSkill4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSkill4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSkill4ActionPerformed

    private void txtJobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJobActionPerformed

    private void txtEmployerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmployerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmployerActionPerformed

    private void txtJobCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJobCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJobCityActionPerformed

    private void txtJobStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJobStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJobStateActionPerformed

    private void txtJobSYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJobSYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJobSYearActionPerformed

    private void txtJobEYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJobEYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJobEYearActionPerformed

    private void txtLang1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLang1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLang1ActionPerformed

    private void txtLang2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLang2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLang2ActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        
        
        
        int p = JOptionPane.showConfirmDialog(null, "Are you sure you want to add record?","Add Record",JOptionPane.YES_NO_OPTION);
        if(p==0){        // TODO add your handling code here:

            try {
                conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/resume_maker", "root", "");

                String sql ="INSERT INTO `resume_info`(`objective`, `name`, `last_name`, `profession`, `city`, `state`, `zip_code`, `phone_no`, `email`, `college_name`, `college_location`, `degree`, `field_of_study`, "
               +"`graduation_start_year`, `graduation_end_year`, `skill1`, `skill2`, `skill3`, `skill4`, `job`, `employer`, `job_city`, `job_state`, `job_start_year`, `job_end_year`, `job_discription`, `language1`, `language2`)"
                        +"VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";

                pst=conn.prepareStatement(sql);
                pst.setString(1,txtObjective.getText());
                pst.setString(2,txtName.getText());
                pst.setString(3,txtLastName.getText());
                pst.setString(4,txtPro.getText());
                pst.setString(5,txtCity.getText());
                pst.setString(6,txtState.getText());
                pst.setString(7,txtCode.getText());
                pst.setString(8,txtPhone.getText());
                pst.setString(9,txtEmail.getText());
                pst.setString(10,txtClg.getText());
                pst.setString(11,txtClgLoc.getText());
                pst.setString(12,txtDegree.getText());
                pst.setString(13,txtFOS.getText());
                pst.setString(14,txtSYear.getText());
                pst.setString(15,txtEYear.getText());
                pst.setString(16,txtSkill1.getText());
                pst.setString(17,txtSkill2.getText());
                pst.setString(18,txtSkill3.getText());
                pst.setString(19,txtSkill4.getText());
                pst.setString(20,txtJob.getText());
                pst.setString(21,txtEmployer.getText());
                pst.setString(22,txtJobCity.getText());
                pst.setString(23,txtJobState.getText());
                pst.setString(24,txtJobSYear.getText());
                pst.setString(25,txtJobEYear.getText());
                pst.setString(26,txtJobDis.getText());
                pst.setString(27,txtLang1.getText());
                pst.setString(28,txtLang2.getText());

                pst.execute();
                JOptionPane.showMessageDialog(null,"Data is saved successfully");

            }
            catch (Exception e)

            {
                JOptionPane.showMessageDialog(null,e);
            }
            finally {

                try{
                    rs.close();
                    pst.close();

                }
                catch(Exception e){

                }
            }
        }
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateActionPerformed
     
        JFileChooser dialog = new JFileChooser();
        dialog.setSelectedFile(new File(txtName.getText()+" "+txtLastName.getText()+"-Resume"+".pdf"));
        int dialogResult = dialog.showSaveDialog(null);
        if (dialogResult==JFileChooser.APPROVE_OPTION){
            String filePath = dialog.getSelectedFile().getPath();

            try {
                // TODO add your handling code here:
                Document myDocument = new Document();
                PdfWriter myWriter = PdfWriter.getInstance(myDocument, new FileOutputStream(filePath));

                myDocument.open();

                PdfPTable table = new PdfPTable(2);
                //table.getDefaultCell().setBorder(0);

                myDocument.add(new Paragraph(txtName.getText()+" "+txtLastName.getText(),FontFactory.getFont(FontFactory.TIMES_BOLD,32,Font.BOLD,BaseColor.DARK_GRAY )));
                myDocument.add(new Paragraph("",FontFactory.getFont(FontFactory.TIMES_BOLD,9,Font.PLAIN,BaseColor.DARK_GRAY)));
                myDocument.add(new Paragraph("",FontFactory.getFont(FontFactory.TIMES_BOLD,9,Font.PLAIN,BaseColor.DARK_GRAY)));
                myDocument.add(new Paragraph("----------------------------------------------------------------------------------------------------------------------------------"));
                myDocument.add(new Paragraph("CONTACT DETAILS",FontFactory.getFont(FontFactory.TIMES_BOLD,9,Font.BOLD,BaseColor.DARK_GRAY )));
                myDocument.add(new Paragraph(txtEmail.getText(),FontFactory.getFont(FontFactory.TIMES_BOLD,7,Font.PLAIN,BaseColor.DARK_GRAY  )));
                myDocument.add(new Paragraph("+91 "+txtPhone.getText(),FontFactory.getFont(FontFactory.TIMES_BOLD,7,Font.PLAIN ,BaseColor.DARK_GRAY )));
                myDocument.add(new Paragraph(txtCity.getText() +", "+txtState.getText()+", "+txtCode.getText(),FontFactory.getFont(FontFactory.TIMES_BOLD,7,Font.PLAIN,BaseColor.DARK_GRAY  )));
                
                myDocument.add(new Paragraph("----------------------------------------------------------------------------------------------------------------------------------"));
                myDocument.add(new Paragraph("OBJECTIVE",FontFactory.getFont(FontFactory.TIMES_BOLD,9,Font.BOLD,BaseColor.DARK_GRAY )));
                myDocument.add(new Paragraph(txtObjective.getText(),FontFactory.getFont(FontFactory.TIMES_BOLD,7,Font.PLAIN,BaseColor.DARK_GRAY  )));
                myDocument.add(new Paragraph("----------------------------------------------------------------------------------------------------------------------------------"));
                myDocument.add(new Paragraph("SKILLS",FontFactory.getFont(FontFactory.TIMES_BOLD,9,Font.BOLD,BaseColor.DARK_GRAY  )));
                table.setHeaderRows(1);
                /*PdfPCell cell;
                cell = new PdfPCell(new Phrase("The below are my skills"));
                cell.setColspan(1);
                table.addCell(cell);
                cell = new PdfPCell(new Phrase("SKILLS"));
                cell.setRowspan(1);
                table.addCell(cell);*/
                table.addCell(txtSkill1.getText());
                table.addCell(txtSkill2.getText());
                table.addCell(txtSkill3.getText());
                table.addCell(txtSkill4.getText());
                myDocument.add(table);
                myDocument.add(new Paragraph("----------------------------------------------------------------------------------------------------------------------------------"));
                myDocument.add(new Paragraph("QUALIFICATIONS",FontFactory.getFont(FontFactory.TIMES_BOLD,9,Font.BOLD,BaseColor.DARK_GRAY  )));
                myDocument.add(new Paragraph(txtClg.getText(),FontFactory.getFont(FontFactory.TIMES_BOLD,7,Font.PLAIN,BaseColor.DARK_GRAY  )));
                myDocument.add(new Paragraph(txtDegree.getText()+" , "+txtFOS.getText(),FontFactory.getFont(FontFactory.TIMES_BOLD,7,Font.PLAIN,BaseColor.DARK_GRAY  )));
                myDocument.add(new Paragraph(txtSYear.getText()+"-"+txtEYear.getText(),FontFactory.getFont(FontFactory.TIMES_BOLD,7,Font.PLAIN,BaseColor.DARK_GRAY  )));
                myDocument.add(new Paragraph("----------------------------------------------------------------------------------------------------------------------------------"));
                myDocument.add(new Paragraph("WORK EXPERIENCE",FontFactory.getFont(FontFactory.TIMES_BOLD,10,Font.BOLD,BaseColor.DARK_GRAY  )));
                myDocument.add(new Paragraph(txtJob.getText()+System.lineSeparator()+txtEmployer.getText(),FontFactory.getFont(FontFactory.TIMES_BOLD,7,Font.PLAIN,BaseColor.DARK_GRAY)));
                myDocument.add(new Paragraph(txtJobCity.getText()+" , "+txtJobState.getText(),FontFactory.getFont(FontFactory.TIMES_BOLD,7,Font.PLAIN,BaseColor.DARK_GRAY)));
                myDocument.add(new Paragraph(txtJobSYear.getText()+"-"+txtJobEYear.getText(),FontFactory.getFont(FontFactory.TIMES_BOLD,7,Font.PLAIN,BaseColor.DARK_GRAY  )));
                myDocument.add(new Paragraph(txtJobDis.getText(),FontFactory.getFont(FontFactory.TIMES_BOLD,7,Font.PLAIN,BaseColor.DARK_GRAY)));
                myDocument.add(new Paragraph("----------------------------------------------------------------------------------------------------------------------------------"));
                myDocument.add(new Paragraph("LANGUAGES",FontFactory.getFont(FontFactory.TIMES_BOLD,9,Font.BOLD,BaseColor.DARK_GRAY  )));
                myDocument.add(new Paragraph(txtLang1.getText()+System.lineSeparator()+txtLang2.getText(),FontFactory.getFont(FontFactory.TIMES_BOLD,7,Font.PLAIN,BaseColor.DARK_GRAY  )));
                myDocument.add(new Paragraph("----------------------------------------------------------------------------------------------------------------------------------"));
                myDocument.add(new Paragraph("REFERENCES",FontFactory.getFont(FontFactory.TIMES_BOLD,9,Font.BOLD,BaseColor.DARK_GRAY  )));
                myDocument.add(new Paragraph("--------//--------",FontFactory.getFont(FontFactory.TIMES_BOLD,6,Font.PLAIN,BaseColor.DARK_GRAY  )));
                myDocument.add(new Paragraph("----//----//------",FontFactory.getFont(FontFactory.TIMES_BOLD,6,Font.PLAIN,BaseColor.DARK_GRAY  )));

                myDocument.close();
                JOptionPane.showMessageDialog(null,"Resume was successfully generated");

            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
            finally {

                try{
                    rs.close();
                    pst.close();

                }
                catch(Exception e){

                }
            }
        }
    }//GEN-LAST:event_btnGenerateActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null,"Do You Really Want To Close Application","SELECT",JOptionPane.YES_NO_OPTION);
        if(a==0){
            System.exit(0);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void txtSkill1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSkill1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_UP){
            txtPhone.requestFocus();
        }
        if(evt.getKeyCode()==KeyEvent.VK_RIGHT){
            txtJob.requestFocus();
        }
        if(evt.getKeyCode()==KeyEvent.VK_DOWN){
            txtSkill2.requestFocus();
        }
           
    }//GEN-LAST:event_txtSkill1KeyPressed

    private void txtSkill2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSkill2KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_UP){
            txtSkill1.requestFocus();
        }
        if(evt.getKeyCode()==KeyEvent.VK_RIGHT){
            txtJobCity.requestFocus();
        }
        if(evt.getKeyCode()==KeyEvent.VK_DOWN){
            txtSkill3.requestFocus();
        }
    }//GEN-LAST:event_txtSkill2KeyPressed

    private void txtSkill3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSkill3KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_UP){
            txtSkill2.requestFocus();
        }
        if(evt.getKeyCode()==KeyEvent.VK_RIGHT){
            txtJobSYear.requestFocus();
        }
        if(evt.getKeyCode()==KeyEvent.VK_DOWN){
            txtSkill4.requestFocus();
        }
    }//GEN-LAST:event_txtSkill3KeyPressed

    private void txtSkill4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSkill4KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_UP){
            txtSkill3.requestFocus();
        }
        if(evt.getKeyCode()==KeyEvent.VK_RIGHT){
            txtJobDis.requestFocus();
        }
        
    }//GEN-LAST:event_txtSkill4KeyPressed

    private void txtLang1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLang1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_UP){
            txtEYear.requestFocus();
        }
        if(evt.getKeyCode()==KeyEvent.VK_LEFT){
            txtEmployer.requestFocus();
        }
        if(evt.getKeyCode()==KeyEvent.VK_DOWN){
            txtLang2.requestFocus();
        }
    }//GEN-LAST:event_txtLang1KeyPressed

    private void txtLang2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLang2KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_UP){
            txtLang1.requestFocus();
        }
        if(evt.getKeyCode()==KeyEvent.VK_LEFT){
            txtJobState.requestFocus();
        }
        
    }//GEN-LAST:event_txtLang2KeyPressed

    private void txtJobKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJobKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_UP){
            txtEmail.requestFocus();
        }
        if(evt.getKeyCode()==KeyEvent.VK_LEFT){
            txtSkill1.requestFocus();
        }
        if(evt.getKeyCode()==KeyEvent.VK_DOWN){
            txtJobCity.requestFocus();
        }
        if(evt.getKeyCode()==KeyEvent.VK_RIGHT){
            txtEmployer.requestFocus();
        }
    }//GEN-LAST:event_txtJobKeyPressed

    private void txtEmployerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmployerKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_UP){
            txtSYear.requestFocus();
        }
        if(evt.getKeyCode()==KeyEvent.VK_LEFT){
            txtJob.requestFocus();
        }
        if(evt.getKeyCode()==KeyEvent.VK_DOWN){
            txtJobState.requestFocus();
        }
        if(evt.getKeyCode()==KeyEvent.VK_RIGHT){
            txtLang1.requestFocus();
        }
    }//GEN-LAST:event_txtEmployerKeyPressed

    private void txtJobCityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJobCityKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_UP){
            txtJob.requestFocus();
        }
        if(evt.getKeyCode()==KeyEvent.VK_LEFT){
            txtSkill2.requestFocus();
        }
        if(evt.getKeyCode()==KeyEvent.VK_DOWN){
            txtJobSYear.requestFocus();
        }
        if(evt.getKeyCode()==KeyEvent.VK_RIGHT){
            txtJobState.requestFocus();
        }
    }//GEN-LAST:event_txtJobCityKeyPressed

    private void txtJobStateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJobStateKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_UP){
            txtEmployer.requestFocus();
        }
        if(evt.getKeyCode()==KeyEvent.VK_LEFT){
            txtJobCity.requestFocus();
        }
        if(evt.getKeyCode()==KeyEvent.VK_DOWN){
            txtJobEYear.requestFocus();
        }
        if(evt.getKeyCode()==KeyEvent.VK_RIGHT){
            txtLang2.requestFocus();
        }
    }//GEN-LAST:event_txtJobStateKeyPressed

    private void txtJobSYearKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJobSYearKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_UP){
            txtJobCity.requestFocus();
        }
        if(evt.getKeyCode()==KeyEvent.VK_LEFT){
            txtSkill3.requestFocus();
        }
        if(evt.getKeyCode()==KeyEvent.VK_DOWN){
            txtJobDis.requestFocus();
        }
        if(evt.getKeyCode()==KeyEvent.VK_RIGHT){
            txtJobEYear.requestFocus();
        }
    }//GEN-LAST:event_txtJobSYearKeyPressed

    private void txtJobEYearKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJobEYearKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_UP){
            txtJobState.requestFocus();
        }
        if(evt.getKeyCode()==KeyEvent.VK_LEFT){
            txtJobSYear.requestFocus();
        }
        if(evt.getKeyCode()==KeyEvent.VK_DOWN){
            txtJobDis.requestFocus();
        }
        if(evt.getKeyCode()==KeyEvent.VK_RIGHT){
            txtLang2.requestFocus();
        }
    }//GEN-LAST:event_txtJobEYearKeyPressed

    private void txtJobDisKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJobDisKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_UP){
            txtJobEYear.requestFocus();
        }
        if(evt.getKeyCode()==KeyEvent.VK_LEFT){
            txtSkill4.requestFocus();
        }
   
        if(evt.getKeyCode()==KeyEvent.VK_RIGHT){
            txtLang2.requestFocus();
        }
    }//GEN-LAST:event_txtJobDisKeyPressed

    private void txtObjectiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtObjectiveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtObjectiveActionPerformed

    private void txtObjectiveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtObjectiveKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_DOWN){
            txtName.requestFocus();
        }
     
    }//GEN-LAST:event_txtObjectiveKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResumeM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResumeM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResumeM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResumeM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResumeM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnGenerate;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtClg;
    private javax.swing.JTextField txtClgLoc;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtDegree;
    private javax.swing.JTextField txtEYear;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmployer;
    private javax.swing.JTextField txtFOS;
    private javax.swing.JTextField txtJob;
    private javax.swing.JTextField txtJobCity;
    private javax.swing.JTextArea txtJobDis;
    private javax.swing.JTextField txtJobEYear;
    private javax.swing.JTextField txtJobSYear;
    private javax.swing.JTextField txtJobState;
    private javax.swing.JTextField txtLang1;
    private javax.swing.JTextField txtLang2;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtObjective;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtPro;
    private javax.swing.JTextField txtSYear;
    private javax.swing.JTextField txtSkill1;
    private javax.swing.JTextField txtSkill2;
    private javax.swing.JTextField txtSkill3;
    private javax.swing.JTextField txtSkill4;
    private javax.swing.JTextField txtState;
    // End of variables declaration//GEN-END:variables
private ImageIcon format =null;
    //strin filename
    String filename = null;
    byte[] person_image = null;
    
    private String gender;

}
